language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5"
  - "3.6-dev" # 3.6 development branch
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests
script:
  - pytest Tests/test_user.py
  - py.test --basetemp=dir Tests/test_user.py
  - py.test --basetemp=dir Tests/test_list.py
  - py.test Tests/test_user.py --doctest-modules
  - py.test Tests/test_list.py --doctest-modules
  # - pytest Tests/base_tests.py
  # - py.test --basetemp=dir Tests/base_tests.py
  # - py.test --cov=app Tests/*
# run coveralls after success
after_success: coveralls
cache: pip